# Dataset reader arguments
dataset:
  source_dir: 'data/dense_mels'

# Model related arguments
model:
  dummy: 0

transformer:
  pre_lnorm: False
  dropout: 0
  dropatt: 0
  d_model: 80
  d_inner: 64
  n_head: 4
  d_head: 16
  d_style: 512
  n_layer: 4
  tgt_len: 128
  mem_len: 128
  ext_len: 128
  attn_type: 0
  same_len: True
  clamp_len: 256
